name: AzureTFDeploy

on:
  pull_request:

  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Directory
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - directory: azure-dev-infra
            auto_apply: no 
          - directory: azuread-users-groups-roles
            auto_apply: no             
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
        shell: bash
    
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}      

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

#      - name: Az CLI login
#        uses: azure/login@v1
#        with:
#          client-id: ${{ secrets.ARM_CLIENT_ID }}
#          tenant-id: ${{ secrets.ARM_CLIENT_SECRET }}
#          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}      

      - name: "Terraform Format"
        id: fmt
        run: terraform fmt

      - name: "Terraform Init"
        id: init
        run: terraform init

      - name: "Terraform Validate"
        id: validate
        run: terraform validate -no-color        
